image:
  repository: 891377024254.dkr.ecr.eu-north-1.amazonaws.com/lesson-5-ecr
  tag: v1.0.8
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config: # Змінні середовища (env) з 4-ї теми
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
